`include "defs.svh"

// Hardcoded rsqrt seed LUT (32 entries, 64-bit each).
// Index = {parity, mantissa}: parity selects octave [1,2) vs [2,4),
// mantissa selects 1-of-16 sub-intervals within that octave.
// Values match newton_lut.hex generated by: make lut
module newton_lut(
    input  logic                parity,
    input  logic [`LUTBITS-1:0] mantissa,
    output dword_t              val
);
    always_comb begin
        case ({parity, mantissa})
            // parity=0: octave [1,2)
            5'd0:  val = 64'h000000000fc17644; // rsqrt(1.031250) = 0.984732
            5'd1:  val = 64'h000000000f4c866d; // rsqrt(1.093750) = 0.956183
            5'd2:  val = 64'h000000000ee133df; // rsqrt(1.156250) = 0.929981
            5'd3:  val = 64'h000000000e7e3ed2; // rsqrt(1.218750) = 0.905822
            5'd4:  val = 64'h000000000e229ec8; // rsqrt(1.281250) = 0.883452
            5'd5:  val = 64'h000000000dcd76dd; // rsqrt(1.343750) = 0.862662
            5'd6:  val = 64'h000000000d7e0cec; // rsqrt(1.406250) = 0.843274
            5'd7:  val = 64'h000000000d33c2da; // rsqrt(1.468750) = 0.825137
            5'd8:  val = 64'h000000000cee115f; // rsqrt(1.531250) = 0.808122
            5'd9:  val = 64'h000000000cac83f6; // rsqrt(1.593750) = 0.792118
            5'd10: val = 64'h000000000c6eb5a3; // rsqrt(1.656250) = 0.777029
            5'd11: val = 64'h000000000c344e64; // rsqrt(1.718750) = 0.762770
            5'd12: val = 64'h000000000bfd0120; // rsqrt(1.781250) = 0.749269
            5'd13: val = 64'h000000000bc889f6; // rsqrt(1.843750) = 0.736460
            5'd14: val = 64'h000000000b96ace2; // rsqrt(1.906250) = 0.724286
            5'd15: val = 64'h000000000b673499; // rsqrt(1.968750) = 0.712697
            // parity=1: octave [2,4)
            5'd16: val = 64'h000000000b24169c; // rsqrt(2.062500) = 0.696311
            5'd17: val = 64'h000000000ad166c6; // rsqrt(2.187500) = 0.676123
            5'd18: val = 64'h000000000a858354; // rsqrt(2.312500) = 0.657596
            5'd19: val = 64'h000000000a3f8a28; // rsqrt(2.437500) = 0.640513
            5'd20: val = 64'h0000000009fec03c; // rsqrt(2.562500) = 0.624695
            5'd21: val = 64'h0000000009c2895d; // rsqrt(2.687500) = 0.609994
            5'd22: val = 64'h00000000098a61ed; // rsqrt(2.812500) = 0.596285
            5'd23: val = 64'h000000000955da1e; // rsqrt(2.937500) = 0.583460
            5'd24: val = 64'h0000000009249249; // rsqrt(3.062500) = 0.571429
            5'd25: val = 64'h0000000008f63809; // rsqrt(3.187500) = 0.560112
            5'd26: val = 64'h0000000008ca83f6; // rsqrt(3.312500) = 0.549442
            5'd27: val = 64'h0000000008a137d6; // rsqrt(3.437500) = 0.539360
            5'd28: val = 64'h00000000087a1d23; // rsqrt(3.562500) = 0.529813
            5'd29: val = 64'h00000000085503df; // rsqrt(3.687500) = 0.520756
            5'd30: val = 64'h000000000831c199; // rsqrt(3.812500) = 0.512148
            5'd31: val = 64'h00000000081030a2; // rsqrt(3.937500) = 0.503953
            default: val = 64'h0;
        endcase
    end
endmodule
