// gen_lut.c  --  run once to emit newton_lut.c and rtl/newton_lut.hex
// Compile:  gcc gen_lut.c -o gen_lut -lm
// Run:      ./gen_lut > newton_lut.c
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include "definitions.h"   // for NEWTON_LUT_BITS, SEED_FRAC, NEWTON_LUT_SIZE

int main(void) {
    int K = NEWTON_LUT_BITS;
    int entries = 1 << K;

    // table[octave*entries + m] -- same flat order newton_lut.sv's
    // dword_t lut[1:0][LUTSIZE-1:0] expects from $readmemh (row-major:
    // first index slowest, i.e. octave 0's entries then octave 1's).
    int64_t table[NEWTON_LUT_SIZE];
    double  v_table[NEWTON_LUT_SIZE];
    double  y_table[NEWTON_LUT_SIZE];

    for (int octave = 0; octave < 2; octave++) {
        double base = (octave == 0) ? 1.0 : 2.0;   // [1,2) or [2,4)
        double span = (octave == 0) ? 1.0 : 2.0;
        for (int m = 0; m < entries; m++) {
            double v = base + span * ((m + 0.5) / entries);  // entry midpoint
            double y = 1.0 / sqrt(v);                        // true rsqrt
            int idx = octave * entries + m;
            table[idx]   = (int64_t)(y * ((int64_t)1 << SEED_FRAC) + 0.5);
            v_table[idx] = v;
            y_table[idx] = y;
        }
    }

    printf("// AUTO-GENERATED by gen_lut.c -- do not edit by hand.\n");
    printf("// rsqrt seed table for [1,4), K=%d bits/octave, Q%d output.\n",
           K, SEED_FRAC);
    printf("#ifndef NEWTON_LUT_C\n");
    printf("#define NEWTON_LUT_C\n\n");
    printf("#include \"definitions.h\"\n\n");
    printf("const int64_t NEWTON_LUT[NEWTON_LUT_SIZE] = {\n");
    for (int octave = 0; octave < 2; octave++) {
        for (int m = 0; m < entries; m++) {
            int idx = octave * entries + m;
            printf("    %lldLL,   // [%d][%3d] rsqrt(%.6f) = %.6f\n",
                   (long long)table[idx], octave, m, v_table[idx], y_table[idx]);
        }
    }
    printf("};\n\n");
    printf("#endif // NEWTON_LUT_C\n");

    // also emit the same table as a $readmemh-compatible hex file for
    // rtl/newton_lut.sv, which loads it into dword_t lut[1:0][LUTSIZE-1:0].
    // path is repo-root-relative, same convention as bitlevel_model.c's
    // "output/states.csv".
    FILE *hf = fopen("rtl/newton_lut.hex", "w");
    if (!hf) {
        perror("fopen rtl/newton_lut.hex");
        return 1;
    }
    fprintf(hf, "// AUTO-GENERATED by gen_lut.c -- do not edit by hand.\n");
    fprintf(hf, "// $readmemh table for newton_lut.sv: dword_t lut[1:0][LUTSIZE-1:0]\n");
    for (int octave = 0; octave < 2; octave++) {
        for (int m = 0; m < entries; m++) {
            int idx = octave * entries + m;
            fprintf(hf, "%016llx // [%d][%3d] rsqrt(%.6f) = %.6f\n",
                    (unsigned long long)table[idx], octave, m, v_table[idx], y_table[idx]);
        }
    }
    fclose(hf);

    return 0;
}
