// gen_st_init.c -- generates a $readmemh-compatible memory file holding the
// fixed-point initial State (positions/velocities/mass plus seeded
// accelerations) for one orbit config, for accelerator_tb.sv to load into
// st_init. Uses bitlevel_model.h's bit-exact seed_accelerations (the same
// LUT/Newton-Raphson rsqrt path as bitlevel_model.c and the RTL), not a
// simplified double-precision approximation -- for well-behaved orbits the
// difference is negligible, but for chaotic configs even a couple ULPs of
// seed mismatch diverges into a completely different trajectory within
// ~100 steps.
// Compile:  gcc modeling/gen_st_init.c modeling/orbits.c -o modeling/gen_st_init.exe -lm
// Run:      ./modeling/gen_st_init.exe figure8
#include <stdio.h>
#include <stdint.h>

#include "bitlevel_model.h"
#include "orbits.h"

static inline int32_t to_fixed(double x) {
    return (int32_t)llround(x * (double)FRAC_SCALE);
}

int main(int argc, char *argv[]) {
    const char *orbit_name = (argc > 1) ? argv[1] : "figure8";

    State state;
    double dt = load_orbit_config(orbit_name, &state);
    seed_accelerations(&state);

    const char *path = "simulation/st_init.mem";
    FILE *f = fopen(path, "w");
    if (!f) {
        perror("fopen");
        return 1;
    }

    fprintf(f, "// AUTO-GENERATED by gen_st_init.c -- do not edit by hand.\n");
    fprintf(f, "// $readmemh initial state for orbit '%s', Q%u fixed point.\n", orbit_name, FRAC_BITS);
    fprintf(f, "// suggested dt = %.10g (0x%08x)\n", dt, (uint32_t)to_fixed(dt));
    fprintf(f, "// layout: %d values per field, field order rx,ry,rz,vx,vy,vz,ax,ay,az,m\n", N);

    static const char *field_names[10] = {"rx", "ry", "rz", "vx", "vy", "vz", "ax", "ay", "az", "m"};
    int32_t *fields[10] = {
        state.rx, state.ry, state.rz,
        state.vx, state.vy, state.vz,
        state.ax, state.ay, state.az,
        state.m,
    };

    for (int fld = 0; fld < 10; fld++) {
        for (int i = 0; i < N; i++) {
            fprintf(f, "%08x // %s[%d] = %.10g\n",
                    (uint32_t)fields[fld][i], field_names[fld], i,
                    fields[fld][i] / (double)FRAC_SCALE);
        }
    }

    fclose(f);
    printf("wrote %s (orbit=%s, dt=%.10g)\n", path, orbit_name, dt);
    return 0;
}
