`timescale 1ns / 1ps
`include "../rtl/defs.svh"

module accelerator_tb;

    logic clk;
    logic rst;
    logic restart;
    State st_init;
    word_t dt;
    word_t tend;
    State st_out;
    logic done;
    word_t state_counter;

    accelerator dut (
        .clk(clk),
        .rst(rst),
        .restart(restart),
        .st_init(st_init),
        .dt(dt),
        .tend(tend),
        .st_out(st_out),
        .done(done),
        .state_counter(state_counter)
    );

    always #5 clk = ~clk;

    // flat $readmemh target for st_init.mem, generated by modeling/gen_st_init.c;
    // field order rx,ry,rz,vx,vy,vz,ax,ay,az,m, `N values per field
    word_t st_init_mem [10*`N-1:0];

    int csv_file;

    // one row per particle, dequantized to real values; matches the
    // step,t,particle,rx,ry,rz,vx,vy,vz,ax,ay,az,m layout written by
    // modeling/export.py and modeling/bitlevel_model.c's write_states_csv
    function void write_state_csv(int step, State st);
        real t_real;
        t_real = real'(step) * (real'(dt) / real'(`FRACSCALE));
        for (int p = 0; p < `N; p++) begin
            $fwrite(csv_file, "%0d,%.10g,%0d,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g\n",
                step, t_real, p,
                real'(st.rx[p]) / real'(`FRACSCALE),
                real'(st.ry[p]) / real'(`FRACSCALE),
                real'(st.rz[p]) / real'(`FRACSCALE),
                real'(st.vx[p]) / real'(`FRACSCALE),
                real'(st.vy[p]) / real'(`FRACSCALE),
                real'(st.vz[p]) / real'(`FRACSCALE),
                real'(st.ax[p]) / real'(`FRACSCALE),
                real'(st.ay[p]) / real'(`FRACSCALE),
                real'(st.az[p]) / real'(`FRACSCALE),
                real'(st.m[p])  / real'(`FRACSCALE));
        end
    endfunction

    initial begin
        $dumpfile("../output/waves.vcd");
        $dumpvars(0, accelerator_tb);

        $display("Starting accelerator VCS testbench...");
        clk = 0;
        rst = 1;
        restart = 0;
        dt = 0;
        tend = 0;

        // load the orbit config baked into st_init.mem (make st_init ORBIT=<config>)
        $readmemh("st_init.mem", st_init_mem);
        for (int i = 0; i < `N; i++) begin
            st_init.rx[i] = st_init_mem[0*`N + i];
            st_init.ry[i] = st_init_mem[1*`N + i];
            st_init.rz[i] = st_init_mem[2*`N + i];
            st_init.vx[i] = st_init_mem[3*`N + i];
            st_init.vy[i] = st_init_mem[4*`N + i];
            st_init.vz[i] = st_init_mem[5*`N + i];
            st_init.ax[i] = st_init_mem[6*`N + i];
            st_init.ay[i] = st_init_mem[7*`N + i];
            st_init.az[i] = st_init_mem[8*`N + i];
            st_init.m[i]  = st_init_mem[9*`N + i];
        end

        #20;
        rst = 0;
        // dt=0.01 matches every config's suggested dt in modeling/orbits.py
        // (re-check this if a future config uses a different one).
        // tend=10.0 (~1000 steps) matches fm/blm's default t_end, so
        // make fm / make blm / make simulate are directly comparable
        dt = 32'h000028f6;
        tend = 32'h0c000000;

        csv_file = $fopen("../output/states.csv", "w");
        $fwrite(csv_file, "step,t,particle,rx,ry,rz,vx,vy,vz,ax,ay,az,m\n");

        #10;
        restart = 1;
        #10;
        restart = 0;

        @(posedge clk);  // let cur_state <= st_init land before reading st_out
        write_state_csv(0, st_out);

        begin
            int last_counter;
            last_counter = 0;
            while (!done) begin
                @(posedge clk);
                if (state_counter != last_counter) begin
                    last_counter = state_counter;
                    write_state_csv(last_counter, st_out);
                end
            end
        end

        $fclose(csv_file);
        $display("Simulation finished at time %0t", $time);
        $finish;
    end

endmodule
