`timescale 1ns / 1ps
`include "../rtl/defs.svh"

module accelerator_tb;

    logic clk;
    logic rst;
    logic restart;
    State st_init;
    word_t dt;
    word_t tend;
    State st_out;
    logic done;
    word_t state_counter;
    int cycle_counter;

    accelerator dut (
        .clk(clk),
        .rst(rst),
        .restart(restart),
        .st_init(st_init),
        .dt(dt),
        .tend(tend),
        .st_out(st_out),
        .done(done),
        .state_counter(state_counter)
    );

    always #5 clk = ~clk;

    // flat $readmemh target for st_init.mem, generated by modeling/gen_st_init.c;
    // field order rx,ry,rz,vx,vy,vz,ax,ay,az,m, `N values per field
    word_t st_init_mem [10*`N-1:0];

    int csv_file;

    // one row per particle, dequantized to real values; matches the
    // step,t,particle,rx,ry,rz,vx,vy,vz,ax,ay,az,m layout written by
    // modeling/export.py and modeling/bitlevel_model.c's write_states_csv
    function void write_state_csv(int step, State st);
        real t_real;
        t_real = real'(step) * (real'(dt) / real'(`FRACSCALE));
        for (int p = 0; p < `N; p++) begin
            $fwrite(csv_file, "%0d,%.10g,%0d,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g\n",
                step, t_real, p,
                real'(st.rx[p]) / real'(`FRACSCALE),
                real'(st.ry[p]) / real'(`FRACSCALE),
                real'(st.rz[p]) / real'(`FRACSCALE),
                real'(st.vx[p]) / real'(`FRACSCALE),
                real'(st.vy[p]) / real'(`FRACSCALE),
                real'(st.vz[p]) / real'(`FRACSCALE),
                real'(st.ax[p]) / real'(`FRACSCALE),
                real'(st.ay[p]) / real'(`FRACSCALE),
                real'(st.az[p]) / real'(`FRACSCALE),
                real'(st.m[p])  / real'(`FRACSCALE));
        end
    endfunction

    initial begin
        // off by default -- +VCD (make sim VCD=1) opts in: a full-hierarchy
        // dump over a long run (e.g. solar_system's ~80000 steps) can reach
        // tens of GB and blow through a disk quota
        if ($test$plusargs("VCD")) begin
            $dumpfile("../output/waves.vcd");
            $dumpvars(0, accelerator_tb);
        end

        $display("Starting accelerator VCS testbench...");
        clk = 0;
        rst = 1;
        restart = 0;
        dt = 0;
        tend = 0;

        // load the orbit config baked into st_init.mem (make st_init ORBIT=<config>)
        $readmemh("st_init.mem", st_init_mem);
        for (int i = 0; i < `N; i++) begin
            st_init.rx[i] = st_init_mem[0*`N + i];
            st_init.ry[i] = st_init_mem[1*`N + i];
            st_init.rz[i] = st_init_mem[2*`N + i];
            st_init.vx[i] = st_init_mem[3*`N + i];
            st_init.vy[i] = st_init_mem[4*`N + i];
            st_init.vz[i] = st_init_mem[5*`N + i];
            st_init.ax[i] = st_init_mem[6*`N + i];
            st_init.ay[i] = st_init_mem[7*`N + i];
            st_init.az[i] = st_init_mem[8*`N + i];
            st_init.m[i]  = st_init_mem[9*`N + i];
        end

        #20;
        rst = 0;
        // dt=0.0005 matches solar_system's suggested dt in modeling/orbits.csv
        // (re-check this if simulating a config with a different dt).
        // tend=5.0 (~10000 steps) matches float64_model.py's hardcoded
        // t_end, so make fm / make blm / make simulate are directly
        // comparable
        dt = 32'h000028A8;
        tend = 32'h02000000;

        csv_file = $fopen("../output/states.csv", "w");
        $fwrite(csv_file, "step,t,particle,rx,ry,rz,vx,vy,vz,ax,ay,az,m\n");

        #10;
        restart = 1;
        #10;
        restart = 0;

        @(posedge clk);  // let cur_state <= st_init land before reading st_out
        write_state_csv(0, st_out);

        begin
            int last_counter;
            last_counter = 0;
            while (!done) begin
                @(posedge clk);
                if (state_counter != last_counter) begin
                    last_counter = state_counter;
                    if (state_counter % 500 == 0) begin
                        $display("State %0d complete on cycle %0d", state_counter, cycle_counter);
                    end
                    write_state_csv(last_counter, st_out);
                end
                cycle_counter++;
            end
        end

        $fclose(csv_file);
        $display("Simulation finished on state %0d and at cycle %0d", state_counter, cycle_counter);
        $finish;
    end

    // // Print raw Q20 integer forces from accel_modules on first force-done pulse
    // // Compare these directly with BLM to isolate rounding source
    // int force_debug_done;
    // initial force_debug_done = 0;
    // always @(posedge clk) begin
    //     if (!force_debug_done && dut.fe_done && dut.fsm == 3'd2) begin
    //         force_debug_done = 1;
    //         $display("=== RTL step-1 forces (raw Q20 integers) ===");
    //         for (int p = 0; p < `N; p++) begin
    //             $display("  p=%0d  ax=%0d  ay=%0d  az=%0d",
    //                 p,
    //                 $signed(dut.ax_out_lane[p]),
    //                 $signed(dut.ay_out_lane[p]),
    //                 $signed(dut.az_out_lane[p]));
    //         end
    //         // Also print post-KD positions used in force computation
    //         $display("  --- post-KD positions (Q20) ---");
    //         for (int p = 0; p < `N; p++) begin
    //             $display("  p=%0d  rx=%0d  ry=%0d", p,
    //                 $signed(dut.next_state.rx[p]),
    //                 $signed(dut.next_state.ry[p]));
    //         end
    //     end
    // end

    // // Print per-lane forces for FE[0] (body 0) at each batch accumulation, step 1 only
    // // Path: dut.FE[i].acc_i is the accel_module instance inside the generate block
    // int fe0_lane_debug_done;
    // initial fe0_lane_debug_done = 0;
    // always @(posedge clk) begin
    //     if (!fe0_lane_debug_done && dut.FE[0].acc_i.au_valid[0]) begin
    //         if (dut.FE[0].acc_i.cycle_ctr == dut.FE[0].acc_i.num_cycles - 1)
    //             fe0_lane_debug_done = 1;
    //         $display("=== FE[0] batch=%0d per-lane ax (Q20) ===", dut.FE[0].acc_i.cycle_ctr);
    //         $display("  lane0=%0d  lane1=%0d  lane2=%0d  lane3=%0d  sum=%0d",
    //             $signed(dut.FE[0].acc_i.ax_wire[0]),
    //             $signed(dut.FE[0].acc_i.ax_wire[1]),
    //             $signed(dut.FE[0].acc_i.ax_wire[2]),
    //             $signed(dut.FE[0].acc_i.ax_wire[3]),
    //             $signed(dut.FE[0].acc_i.ax_wire[0] + dut.FE[0].acc_i.ax_wire[1] +
    //                     dut.FE[0].acc_i.ax_wire[2] + dut.FE[0].acc_i.ax_wire[3]));
    //         $display("  ax_reg_before=%0d", $signed(dut.FE[0].acc_i.ax_reg));
    //     end
    // end

    // // Print lane2 pipeline inputs exactly when ax_i_reg is computed:
    // // valid_reg=1 but valid_reg2=0 means "one cycle after valid fires, before accumulation".
    // // At this posedge, $display reads PRE-posedge (pre-NBA) values = the inputs to ax_i_reg.
    // int fe0_ax_compute_done;
    // initial fe0_ax_compute_done = 0;
    // always @(posedge clk) begin
    //     if (!fe0_ax_compute_done
    //         && dut.FE[0].acc_i.genblk1[2].au.valid_reg
    //         && !dut.FE[0].acc_i.genblk1[2].au.valid_reg2) begin
    //         fe0_ax_compute_done = 1;
    //         $display("=== Lane2 ax_i_reg compute cycle (valid_reg=1, valid_reg2=0) ===");
    //         $display("  inv_res=%0d  mdx_reg[4]=%0d",
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.inv_res),
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.mdx_reg[4]));
    //         $display("  => expected ax = (%0d * %0d) >>> 28 = %0d",
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.mdx_reg[4]),
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.inv_res),
    //             $signed((dut.FE[0].acc_i.genblk1[2].au.mdx_reg[4]
    //                      * dut.FE[0].acc_i.genblk1[2].au.inv_res) >>> 28));
    //         // Drill into inv_pwr_3d2_unit to see rsqrt and cube intermediates
    //         $display("  ip.rsqrt_out=%0d  ip.inv_pwr=%0d  ip.inv_pwr2=%0d  ip.inv_pwr3=%0d",
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.ip.rsqrt_out),
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.ip.inv_pwr),
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.ip.inv_pwr2),
    //             $signed(dut.FE[0].acc_i.genblk1[2].au.ip.inv_pwr3));
    //     end
    // end

endmodule
