// gen_lut.c  --  run once to emit newton_lut.c
// Compile:  gcc gen_lut.c -o gen_lut -lm
// Run:      ./gen_lut > newton_lut.c
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include "definitions.h"   // for NEWTON_LUT_BITS, SEED_FRAC, NEWTON_LUT_SIZE

int main(void) {
    int K = NEWTON_LUT_BITS;
    int entries = 1 << K;

    printf("// AUTO-GENERATED by gen_lut.c -- do not edit by hand.\n");
    printf("// rsqrt seed table for [1,4), K=%d bits/octave, Q%d output.\n",
           K, SEED_FRAC);
    printf("#ifndef NEWTON_LUT_C\n");
    printf("#define NEWTON_LUT_C\n\n");
    printf("#include \"definitions.h\"\n\n");
    printf("const int64_t NEWTON_LUT[NEWTON_LUT_SIZE] = {\n");

    for (int octave = 0; octave < 2; octave++) {
        double base = (octave == 0) ? 1.0 : 2.0;   // [1,2) or [2,4)
        double span = (octave == 0) ? 1.0 : 2.0;
        for (int m = 0; m < entries; m++) {
            double v = base + span * ((m + 0.5) / entries);  // entry midpoint
            double y = 1.0 / sqrt(v);                        // true rsqrt
            int64_t fixed = (int64_t)(y * ((int64_t)1 << SEED_FRAC) + 0.5);
            printf("    %lldLL,   // [%d][%3d] rsqrt(%.6f) = %.6f\n",
                   (long long)fixed, octave, m, v, y);
        }
    }
    printf("};\n\n");
    printf("#endif // NEWTON_LUT_C\n");
    return 0;
}